
#development version of configuration
server:
  port: 8080

#  database connections
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  #    hikari:
  #      pool-name: HikariCP
  #      maximum-pool-size: 5
  #      connection-timeout: 10000
  #      idle-timeout: 600000
  #      max-lifetime: 1800000
  #      validation-timeout: 1800000
  #      leak-detection-threshold: 0
  #      initialization-fail-timeout: -1


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
    show-sql: true
  security:
    #    oauth2 configurations
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:test-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:test-client-secret}
            #/login/oauth2/code/google
            scope:
              - email
              - profile
              - openid
          github:
            client-id: ${GITHUB_CLIENT_ID:test-client-id}
            client-secret: ${GITHUB_CLIENT_SECRET:test-client-secret}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            #/login/oauth2/code/github
            scope:
              - user:email
              - read:user



#    jpa and hibernate configurations


security:
  jwt:
    secret: ${JWT_SECRET:caa8c11fd6ea53a865b63d73f0a1d09d9c0dab7ebdecd6fef990924f7764233e}
    issuer: ${JWT_ISSUER:api.substring.com}
    access-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS:600}
    refresh-ttl-seconds: ${JWT_REFRESH_TTL_SECONDS:86400}
    refresh-token-cookie-name: ${JWT_REFRESH_COOKIE_NAME:refreshToken}
    cookie-secure: ${JWT_COOKIE_SECURE:true}
    cookie-http-only: ${JWT_COOKIE_SECURE_ONLY:true}
    cookie-same-site: ${JWT_COOKIE_SAME_SITE:lax}
    cookie-domain: ${JWT_COOKIE_DOMAIN:localhost}

app:
  cors:
    front-end-url: ${FRONT_END_URL:http://localhost:5173}
  auth:
    frontend:
      success-redirect: ${FRONT_END_SUCCESS_REDIRECT:http://localhost:5173/oauth/success}
      failure-redirect: ${FRONT_END_FAILURE_REDIRECT:http://localhost:5173/oauth/failure}



